---
services:
  etsy_parse:
    image: python:3.13-slim-bullseye
    container_name: etsy-parse
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    command: bash -c "pip install setuptools --upgrade --user && pip install /app/. --user && python /app/aio_etsy_stats/main.py"
    volumes:
      - .:/app
