---
services:
  wireguard-aio_etsy_stats:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-aio_etsy_stats
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - LOG_CONFS=true #optional
    volumes:
      - ${WG_CONFIG_LOC}:/config
    ports:
      - 51820:51820/udp
      - 4444:4444
      - 7900:7900
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:4.27
    container_name: selenium
    network_mode: "service:wireguard-aio_etsy_stats"
    depends_on:
      - wireguard-aio_etsy_stats
    restart: unless-stopped
    shm_size: 2g

  aio_etsy_stats:
    image: ghcr.io/shawnesterman/aio-etsy-stats:main
    container_name: aio_etsy_stats
    network_mode: "service:wireguard-aio_etsy_stats"
    depends_on:
      - wireguard-aio_etsy_stats
    restart: unless-stopped
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - ETSY_STORE_NAME=${ETSY_STORE_NAME}
      - SCRAPE_INTERVAL_MINUTES=${SCRAPE_INTERVAL_MINUTES}
      - DEFAULT_RESET_HOUR=${DEFAULT_RESET_HOUR}
      - AIO_USERNAME=${AIO_USERNAME}
      - AIO_PASSWORD=${AIO_PASSWORD}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - DISCORD_AVATAR_URL=${DISCORD_AVATAR_URL}